openapi: 3.0.3
info:
    title: Johapon v01 API
    version: 0.1.0
servers:
    - url: http://localhost:3000
paths:
    /api/public/health:
        get:
            summary: Health check
            responses:
                '200':
                    description: OK
    /api/public/unions/lookup:
        get:
            summary: Lookup union meta by slug
            parameters:
                - in: query
                  name: slug
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '404':
                    description: Not Found
    /api/tenant/{slug}/meta:
        get:
            summary: Tenant meta
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '404':
                    description: Not Found
    /api/tenant/{slug}/notices:
        get:
            summary: List notices
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: page_size
                  schema:
                      type: integer
                - in: query
                  name: category_key
                  schema:
                      type: string
                - in: query
                  name: subcategory_id
                  schema:
                      type: string
                - in: query
                  name: popup
                  schema:
                      type: boolean
            responses:
                '200':
                    description: OK
        post:
            summary: Create notice
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Created
                '401':
                    description: Unauthorized
    /api/tenant/{slug}/notices/{id}:
        get:
            summary: Get notice detail
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '404':
                    description: Not Found
    patch:
      summary: Update notice
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    delete:
      summary: Delete notice
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
  /api/tenant/{slug}/qna:
    get:
      summary: List QnA
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: Create QnA
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/tenant/{slug}/qna/{id}:
    get:
      summary: Get QnA detail
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    patch:
      summary: Update QnA (answer/status)
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    /api/tenant/{slug}/files:
        get:
            summary: List attachments by target
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
                - in: query
                  name: target_table
                  required: true
                  schema:
                      type: string
                - in: query
                  name: target_id
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
        post:
            summary: Upload & attach file
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '401':
                    description: Unauthorized
    /api/tenant/{slug}/files/{fileId}:
        delete:
            summary: Delete attachment & storage
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
                - in: path
                  name: fileId
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '404':
                    description: Not Found
    /api/tenant/{slug}/slides:
        get:
            summary: List slides
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
                - in: query
                  name: active
                  schema:
                      type: boolean
            responses:
                '200':
                    description: OK
        post:
            summary: Create slide
            parameters:
                - in: path
                  name: slug
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '401':
                    description: Unauthorized
  /api/tenant/{slug}/boards/share:
    get:
      summary: List share board posts
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: Create share board post
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/tenant/{slug}/partners:
    get:
      summary: List partners
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: Create partner
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/tenant/{slug}/partners/{id}:
    get:
      summary: Partner detail
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    patch:
      summary: Update partner
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    delete:
      summary: Delete partner
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
  /api/tenant/{slug}/ads:
    get:
      summary: List ads
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: Create ad
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/tenant/{slug}/metrics/ad-impressions:
    post:
      summary: Log ad impression
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /api/tenant/{slug}/alrimtalk:
    get:
      summary: List alrimtalk logs
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /api/tenant/{slug}/alrimtalk/send:
    post:
      summary: Send alrimtalk (logs only)
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/admin/unions:
    get:
      summary: List unions
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    post:
      summary: Create union
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/admin/users:
    get:
      summary: Search users
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/admin/users/{userId}:
    patch:
      summary: Update user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/admin/users/bulk-upload:
    post:
      summary: Bulk upload users (CSV)
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /api/tenant/{slug}/boards/share/{id}:
    get:
      summary: Get share board post detail
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    patch:
      summary: Update share board post
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    delete:
      summary: Delete share board post
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
  /api/tenant/{slug}/boards/share/{id}/report:
    post:
      summary: Report share board post (not implemented)
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '501':
          description: Not Implemented
  /api/tenant/{slug}/boards/share/{id}/warn:
    post:
      summary: Warn share board post (not implemented)
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '501':
          description: Not Implemented
