import type { Metadata, Viewport } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import { Providers } from '@/app/_lib/shared/tanstack/QueryProvider';
import { ConfirmModal } from '@/app/_lib/widgets/modal';
import { AlertModal } from '@/app/_lib/widgets/modal';

const notoSansKR = Noto_Sans_KR({
    variable: '--font-noto-sans-kr',
    subsets: ['latin'],
    weight: ['400', '500', '700'],
});

export const viewport: Viewport = {
    themeColor: '#f9fafb',
    width: 'device-width',
    initialScale: 1,
    viewportFit: 'cover',
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${notoSansKR.variable} font-sans antialiased`}>
                <Providers>
                    {children}
                    <ConfirmModal />
                    <AlertModal />
                </Providers>
            </body>
        </html>
    );
}
